### ISSUE TITLE
Add Legends component to Plotrb

### ISSUE THREAD

**Issue by zuhao** [SciRuby/plotrb#3]
[Legends](https://github.com/trifacta/vega/wiki/Legends) is added to Vega recently. It has not been incorporated into Plotrb yet. 

We need to add this new component and its DSL to Plortb. For reference, you may take a look at the implementations of other components already in Plotrb.

I've skimmed through Vega's Legends spec, and this task should be pretty straight forward.

**Comment by translunar** [comment]
What's the difficulty on this? You know better than me -- probably intermediate or advanced?

**Comment by papriwalprateek** [comment]
This can be closed now!

**Comment by translunar** [comment]
Okay. FYI, if you put in the commit message something like "Fixes #3", that will cause this to close automatically. =)
