### ISSUE TITLE
Submit plotrb to rubygems

### ISSUE THREAD

**Issue by agarie** [SciRuby/plotrb#9]
I was trying to install plotrb today and discovered that it isn't available via rubygems:

[https://rubygems.org/search?utf8=%E2%9C%93&query=plotrb](https://rubygems.org/search?utf8=%E2%9C%93&query=plotrb)

Is this expected?

In any case, it's pretty easy to submit a new gem: simply use `gem build plotrb.gemspec && gem push plotrb-0.0.x.gem` as can be seen [in this post](http://rubylearning.com/blog/how-do-i-create-and-publish-my-first-ruby-gem/).

**Comment by translunar** [comment]
Wow. I'm kind of shocked we never did that. @Zuhao?

**Comment by translunar** [comment]
Okay, I just went ahead and submitted it. I think that's easier.
